"""
Synthetic targets with a distinctive structural feature, for the
spectrogram-similarity pre-check (spectrogram_similarity.py).

A target generated by the SAME diffusion model as the population
(prior version of this test) is just another random draw from the
population's own distribution -- structurally indistinguishable from
any other candidate. Matching it is the same failure mode as the
earlier rejected "match a random latent point" test: there's no
distinctive feature for evolution to find, so any random candidate
scores about as well as any other, and start/best end up sounding the
same. Found live: user listened to start.wav vs best.wav after a real
run and reported no audible difference (see FINDINGS.md).

Fix: a target with an obvious, distinctive structural feature no
generic "guitar noodling" sample has by chance -- silence, then one
sharp strum, then silence. If the mechanism works, fitness should
climb toward candidates that put their energy in the same place (mid-
clip) instead of spread across the whole clip, and that should be
audible, not just numeric.
"""

from __future__ import annotations

import numpy as np

SAMPLE_RATE = 44100

# Open E major chord (low to high), Hz.
_CHORD_FREQS_HZ = [82.41, 123.47, 164.81, 207.65, 246.94, 329.63]


def build_strum_silence_target(
    duration_s: float = 5.0,
    sr: int = SAMPLE_RATE,
    strum_start_s: float = 1.5,
    decay_s: float = 1.0,
) -> np.ndarray:
    """Silence, then one strummed chord that decays away, then silence.
    Mono float32, peak-normalized to 0.9 (matches mutate_by_rediffusion's
    own convention, keeps loudness comparable across the pipeline)."""
    n_samples = int(round(duration_s * sr))
    t = np.arange(n_samples) / sr
    strum_t = t - strum_start_s

    envelope = np.where(strum_t >= 0, np.exp(-strum_t / decay_s), 0.0)

    audio = np.zeros(n_samples, dtype=np.float64)
    for i, freq in enumerate(_CHORD_FREQS_HZ):
        # tiny detune per string -- avoids a perfectly static, obviously
        # synthetic beating pattern; real strums don't have exact unison
        detune = 1.0 + (i - len(_CHORD_FREQS_HZ) / 2) * 0.0015
        audio += np.sin(2 * np.pi * freq * detune * strum_t) * envelope

    # short noise burst at the attack -- real plucks aren't pure tone
    attack_samples = int(0.02 * sr)
    attack_start = int(round(strum_start_s * sr))
    if attack_start + attack_samples <= n_samples:
        attack_envelope = np.exp(-np.arange(attack_samples) / (0.005 * sr))
        audio[attack_start:attack_start + attack_samples] += (
            np.random.default_rng(0).uniform(-1, 1, attack_samples) * attack_envelope * 0.5
        )

    peak = np.abs(audio).max()
    if peak > 1e-8:
        audio = audio * (0.9 / peak)
    return audio.astype(np.float32)
